backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Noticias/Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Subir Imagen", name: "featured", widget: "image", required: false, hint: "Sube una imagen para el post"}
      - {label: "O URL de Imagen Externa", name: "featureimage", widget: "string", required: false, hint: "URL completa de una imagen externa (si no subiste archivo)"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "tags_array", required: false, hint: "Separa los tags con comas: radio, tecnologia, test"}

  - name: "programas"
    label: "Programas de Radio"
    folder: "content/programas"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - {label: "Nombre del Programa", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Horario", name: "horario", widget: "string"}
      - {label: "Días", name: "dias", widget: "string"}
      - {label: "Conductores", name: "conductores", widget: "string"}
      - {label: "Subir Imagen", name: "featured", widget: "image", required: false}
      - {label: "O URL de Imagen Externa", name: "featureimage", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
